const TerrainType = { PLAIN: 'PLAIN', FOREST: 'FOREST', LIGHT_SPRING: 'LIGHT_SPRING' };
const OrganismType = { GLIMMER: 'GLIMMER', GLOOMER: 'GLOOMER' };
const GlimmerState = { IDLE: 'IDLE', FORAGING: 'FORAGING', FLEEING: 'FLEEING', REPRODUCING: 'REPRODUCING', SOCIALIZING: 'SOCIALIZING' };
const GloomerState = { PATROLLING: 'PATROLLING', CHASING: 'CHASING', AMBUSHING: 'AMBUSHING', RESTING: 'RESTING', STARVING: 'STARVING' };
const GeneticImprint = { FOREST_CHILD: 'FOREST_CHILD', SWIFT: 'SWIFT', VIGILANT: 'VIGILANT', EFFICIENT: 'EFFICIENT', SOCIAL: 'SOCIAL' };
